#!/usr/bin/env bash
# GOAP 3分 Play ゲート上限 — G4c 合格ログ基準 + マージン。
# analyze-phase-d-pass-receive-log.sh から source する単一ソース。
set -euo pipefail

# G1: ShootAtGoal 拒否ループ
GOAP_GATE_MAX_ACTION_REJECTED_SHOOT="${GOAP_GATE_MAX_ACTION_REJECTED_SHOOT:-5}"

# G2/G3: プラン組み立て失敗
GOAP_GATE_MAX_PLAN_FAILURE_FREEBALL="${GOAP_GATE_MAX_PLAN_FAILURE_FREEBALL:-10}"
GOAP_GATE_MAX_PLAN_FAILURE_INCOMING="${GOAP_GATE_MAX_PLAN_FAILURE_INCOMING:-5}"

# G4: シュート直後の NoGoal / 強制守備プラン
GOAP_GATE_MAX_SHOOT_NOGOAL_WINDOW="${GOAP_GATE_MAX_SHOOT_NOGOAL_WINDOW:-3}"
GOAP_GATE_SHOOT_NOGOAL_LINES="${GOAP_GATE_SHOOT_NOGOAL_LINES:-4}"
GOAP_GATE_MIN_FORCED_POST_SHOOT_DEFENSE="${GOAP_GATE_MIN_FORCED_POST_SHOOT_DEFENSE:-1}"

# G4: 敵 NPC NoGoalSelected（G4c: Crocodile 13 / Elephant 2 / 合計 15）
GOAP_GATE_MAX_ENEMY_NOGOAL_CROCODILE="${GOAP_GATE_MAX_ENEMY_NOGOAL_CROCODILE:-20}"
GOAP_GATE_MAX_ENEMY_NOGOAL_ELEPHANT="${GOAP_GATE_MAX_ENEMY_NOGOAL_ELEPHANT:-5}"
GOAP_GATE_MAX_ENEMY_NOGOAL_TOTAL="${GOAP_GATE_MAX_ENEMY_NOGOAL_TOTAL:-25}"

# G6: 味方 NoGoalSelected（G4c: Lion 17 / Gorilla 16 / Boar 11）
GOAP_GATE_MAX_ALLY_NOGOAL_LION="${GOAP_GATE_MAX_ALLY_NOGOAL_LION:-8}"
GOAP_GATE_MAX_ALLY_NOGOAL_GORILLA="${GOAP_GATE_MAX_ALLY_NOGOAL_GORILLA:-8}"
GOAP_GATE_MAX_ALLY_NOGOAL_BOAR="${GOAP_GATE_MAX_ALLY_NOGOAL_BOAR:-8}"

# 全体 NoGoalSelected — G6 目標 < 20（Play 合格後に FAIL へ昇格予定）
GOAP_GATE_WARN_TOTAL_NOGOAL="${GOAP_GATE_WARN_TOTAL_NOGOAL:-25}"

# 移動フリーズ（GoapDiag 座標）— GOAP は動くが足が止まる型（#89 系）
GOAP_FREEZE_WINDOW_SEC="${GOAP_FREEZE_WINDOW_SEC:-5}"
GOAP_FREEZE_DISP_THRESH="${GOAP_FREEZE_DISP_THRESH:-0.2}"
GOAP_FREEZE_MIN_STUCK_ACTORS="${GOAP_FREEZE_MIN_STUCK_ACTORS:-5}"
GOAP_FREEZE_MIN_ACTIVE_ACTORS="${GOAP_FREEZE_MIN_ACTIVE_ACTORS:-4}"
# 必殺中は短時間全員 move が止まるため、8 秒未満は許容
GOAP_FREEZE_MAX_CONTINUOUS_SEC="${GOAP_FREEZE_MAX_CONTINUOUS_SEC:-8}"
# Phase D CLI は Verbose 強制するので Diag 必須にする（run-phase-d が 1 を渡す）
GOAP_FREEZE_REQUIRE_DIAG="${GOAP_FREEZE_REQUIRE_DIAG:-0}"

# Forced→Skip 密度（P0'' 型）— Summary の MoveToDefensive ActionSkipped(context_changed)
GOAP_GATE_WARN_MTD_SKIP_PER_SEC="${GOAP_GATE_WARN_MTD_SKIP_PER_SEC:-15}"
GOAP_GATE_FAIL_MTD_SKIP_BURST_SEC="${GOAP_GATE_FAIL_MTD_SKIP_BURST_SEC:-8}"
