#!/usr/bin/env bash
# GOAP 3分 Play ゲート上限 — G4c 合格ログ基準 + マージン。
# analyze-phase-d-pass-receive-log.sh から source する単一ソース。
set -euo pipefail

# G1: ShootAtGoal 拒否ループ
GOAP_GATE_MAX_ACTION_REJECTED_SHOOT="${GOAP_GATE_MAX_ACTION_REJECTED_SHOOT:-5}"

# G2/G3: プラン組み立て失敗
GOAP_GATE_MAX_PLAN_FAILURE_FREEBALL="${GOAP_GATE_MAX_PLAN_FAILURE_FREEBALL:-10}"
GOAP_GATE_MAX_PLAN_FAILURE_INCOMING="${GOAP_GATE_MAX_PLAN_FAILURE_INCOMING:-5}"

# G4: シュート直後の NoGoal / 強制守備プラン
GOAP_GATE_MAX_SHOOT_NOGOAL_WINDOW="${GOAP_GATE_MAX_SHOOT_NOGOAL_WINDOW:-3}"
GOAP_GATE_SHOOT_NOGOAL_LINES="${GOAP_GATE_SHOOT_NOGOAL_LINES:-4}"
GOAP_GATE_MIN_FORCED_POST_SHOOT_DEFENSE="${GOAP_GATE_MIN_FORCED_POST_SHOOT_DEFENSE:-1}"

# G4: 敵 NPC NoGoalSelected（G4c: Crocodile 13 / Elephant 2 / 合計 15）
GOAP_GATE_MAX_ENEMY_NOGOAL_CROCODILE="${GOAP_GATE_MAX_ENEMY_NOGOAL_CROCODILE:-20}"
GOAP_GATE_MAX_ENEMY_NOGOAL_ELEPHANT="${GOAP_GATE_MAX_ENEMY_NOGOAL_ELEPHANT:-5}"
GOAP_GATE_MAX_ENEMY_NOGOAL_TOTAL="${GOAP_GATE_MAX_ENEMY_NOGOAL_TOTAL:-25}"

# 全体 NoGoalSelected — G6 完了まで WARN のみ（G4c: 59）
GOAP_GATE_WARN_TOTAL_NOGOAL="${GOAP_GATE_WARN_TOTAL_NOGOAL:-80}"
